portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('portfolioapp.urls')),
    path('admin/', admin.site.urls),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

portfolioapp/urls.py
from django.urls import path

from .views import index,contact
                                                                                                             
app_name = "profile"

urlpatterns = [
    path('', index, name='home'),
    path('contact/', contact, name='contact'),
]

portfolioapp/models.py
from django.db import models

#

portfolioapp/views.py
from django.shortcuts import render
#from django.http import HttpResponse
#from .models import CandidateName
#from .models import ProfileContent
#from .models import CollegeName
#from .models import Experience
#from .models import projects
#from .models import Certifications
#from .models import Socialmedia,contacts
#from django.template.context_processors import csrf
from portfolio.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
def index(request):
    return render(request,"index.html")

def contact(request):
    if request.method=="POST":
        fname=request.POST["firstname"]
        lname=request.POST["lastname"]
        cname=request.POST["country"]
        sname=request.POST["subject"]
        email=request.POST["email"]
        message = request.POST["message"] + " from " + email
        #sendemail operations
        send_mail(sname, message, EMAIL_HOST_USER, [EMAIL_HOST_USER], fail_silently = False)
        
    return render(request,"form.html")

templates/1.html
<html>
    <head>

    </head>
    <body>
        <div style="border:1px solid green;overflow:auto;">
        <img src="./girl image1.jpg"style="float:left;"></div>
        <div style="border:1px solid green;overflow:auto; align:center;">
        <p><b>CandidateName</b>:Sudha</p>
        <p><b>ProfileContent</b>:Focused and enthusiastic developer with a keen interest in software development and artificial intelligence. By comprehensive exposure to the underlying concepts and applying them vividly to various projects, 
            my love for these domains came into being. I am a passionate individual who thrives to build and
            apply algorithms to solve real-world industry problems.</p>
        <p><b>CollegeName</b>:PSCMR</p>
        <p><b>Experience</b>:
            <ul>
                <li>Responsible for the design, development, and testing of web-based backend applications to
                     facilitate scalable front-end user interactions through an API.</li>
                <li>Cleaned and processed data into deliverables within specific formats with python libraries.</li>
                <li>working with backend framework such as Django and Flask.</li>
              </ul> 

            
            
            </p>
        <p><b>Projects</b>Efficient Spectrum Utilization using SUCR Protocol.</p>
        <p><b>Certifications</b>Got exposure of working with backend framework such as Django and Flask.</p>


        </div>
    </body>
</html>

templates/backup.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<title>PROFILE</title>
<style>
.imgcontainer {float:left;padding: 10px;}
.container{float:center-right;padding-left: 10px;}
#element1 {float:left;padding: 30px;}
#element2 {float:center-right;width=50;margin-left: 15px;margin-top:20px ;}
#element3 {float:right;}* {box-sizing: border-box;}

/* Style the navbar */
.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
  margin-left: 5px;
  margin-right: 5px;
}

/* Navbar links */
.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

/* Navbar links on mouse-over */
.topnav a:hover {
  background-color: #ddd;
  color: black;
}

/* Active/current link */
.topnav a.active {
  background-color: #2196F3;
  color: white;
}

/* Style the input container */
.topnav .login-container {
  float: right;
}

/* Style the input field inside the navbar */
.topnav input[type=text] {
  padding: 6px;
  margin-top: 8px;
  font-size: 17px;
  border: none;
  width: 150px; /* adjust as needed (as long as it doesn't break the topnav) */
}

/* Style the button inside the input container */
.topnav .login-container button {
  float: right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 16px;
  background: #ddd;
  font-size: 17px;
  border: none;
  cursor: pointer;
}

.topnav .login-container button:hover {
  background: #ccc;
}

/* Add responsiveness - On small screens, display the navbar vertically instead of horizontally */
@media screen and (max-width: 600px) {
  .topnav .login-container {
    float: none;
  }
  .topnav a, .topnav input[type=text], .topnav .login-container button {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  .topnav input[type=text] {
    border: 1px solid #ccc;
  }
}
/* The dropdown container */
.dropdown {
  float: left;
  overflow: hidden;
}

/* Dropdown button */
.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit; /* Important for vertical align on mobile phones */
  margin: 0; /* Important for vertical align on mobile phones */
}

/* Add a red background color to navbar links on hover */
.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}
        
</style>
</head>
<body>    
<div class="topnav" style="background-color:dodgerblue">
    <a class="active" href="{{url_for('main')}}" style="color:white;">Sudha Mullapudi</a>
   <div class="login-container">
    Contact me
    </div>   
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">      
    <i class="fa fa-bars"></i>
  </a>
</div>
    <div class="imgcontainer" id="element1" align="center">
        <div   class="avatar">
             <img src=".\girl image1.jpg" height="510" width="400" alt="OpenPics">      
        </div>
    </div>
            
    <div class="container" id="element2" align = "left-side">
      <div >
        <p><b>CandidateName</b>:Sudha</p>
        <p><b>ProfileContent</b>:Focused and enthusiastic developer with a keen interest in software development and artificial intelligence. By comprehensive exposure to the underlying concepts and applying them vividly to various projects, 
            my love for these domains came into being. I am a passionate individual who thrives to build and
            apply algorithms to solve real-world industry problems.</p>
        <p><b>CollegeName</b>:PSCMR</p>
        <p><b>Experience</b>:
            <ul>
                <li>Responsible for the design, development, and testing of web-based backend applications to
                     facilitate scalable front-end user interactions through an API.</li>
                <li>Cleaned and processed data into deliverables within specific formats with python libraries.</li>
                <li>working with backend framework such as Django and Flask.</li>
              </ul> 

            
            
            </p>
        <p><b>Projects</b>Efficient Spectrum Utilization using SUCR Protocol.</p>
        <p><b>Certifications</b>Got exposure of working with backend framework such as Django and Flask.</p>


        </div>   
  </div>
       
        
<script type='text/javascript'>
function home(){
    var rawText = 1;
    $.get("/home", { value: rawText }).done()}
</script>    
</body>

</html>    

templates/form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<title>PROFILE</title>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/1.css' %}">   
</head>
<body>  
  
  
  
  <header>
    <div class="topnav" style="background-color:dodgerblue">
        <a class="active" href="{% url 'profile:home'  %}" style="color:white;">Sudha Mullapudi</a>
       <div class="login-container">
        <a class="active" href="{% url 'profile:contact'  %}" style="color:white;">Contact me</a>
        </div>   
      <!-- <a href="javascript:void(0);" class="icon" onclick="myFunction()">      
        <i class="fa fa-bars"></i>
      </a> -->
    </div>
    
  </header>






  {% for i in name %}
<div class="topnav" style="background-color:dodgerblue">
    <a class="active" href="{% url 'profile:home'  %}" style="color:white;">{{i.CandidateName_text}}</a>
   <div class="login-container">
    <a class="active" href="{% url 'profile:contact'  %}" style="color:white;">Contact me</a>
    </div>   
    {% endfor %}
  <!-- <a href="javascript:void(0);" class="icon" onclick="myFunction()">      
    <i class="fa fa-bars"></i>
  </a> -->
</div>
 
<div class="container">
    <form action="{% url 'profile:contact' %}" method="POST">
      {% csrf_token %}
      <label for="fname">First Name</label>
      <input type="text" id="fname" name="firstname" placeholder="Your name..">
  
      <label for="lname">Last Name</label>
      <input type="text" id="lname" name="lastname" placeholder="Your last name..">
  
      <label for="country">Country</label>
      <select id="country" name="country">
        <option value="India">India</option>
        <option value="canada">Canada</option>
        <option value="usa">USA</option>
      </select>

      <label for="email">Email</label>
      <input type="text" id="email" name="email" placeholder="Your Email">
      
      <label for="subject">Subject</label>
      <input type="text" id="subject" name="subject" placeholder="Write something..">
      
      <label for="message">Message</label>

      <textarea id="message" name="message" placeholder="Write something.." style="height:200px"></textarea>
  
      <input type="submit" value="Submit">
    </form>
  </div>
  <div class="footer">
  
    <a href="mailto:m9340908@gmail.com" target="_blank" class="fa fa-google"></a>
  
    
    <a href="https://github.com/sudha85" id="fagithub" class="fa fa-github"></a> 
     
    <a href="https://in.linkedin.com/in/sudha-mullapudi-451980202" id="falinkedin" class="fa fa-linkedin"> </a>  
  
  </div> 
  
</body>

</html>    

templates/form1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<title>PROFILE</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/1.css' %}">   
</head>
<body>  
  

  {% for i in name %}
<div class="topnav" style="background-color:dodgerblue">
    <a class="active" href="{% url 'profile:home'  %}" style="color:white;">{{i.CandidateName_text}}</a>
   <div class="login-container">
    <a class="active" href="{% url 'profile:contact'  %}" style="color:white;">Contact me</a>
    </div>   
    {% endfor %}
  <!-- <a href="javascript:void(0);" class="icon" onclick="myFunction()">      
    <i class="fa fa-bars"></i>
  </a> -->
</div>

<div class="container">
    <form action="{% url 'profile:contact' %}" method="POST">
      {% csrf_token %}
      <label for="fname">First Name</label>
      <input type="text" id="fname" name="firstname" placeholder="Your name..">
  
      <label for="lname">Last Name</label>
      <input type="text" id="lname" name="lastname" placeholder="Your last name..">
  
      <label for="country">Country</label>
      <select id="country" name="country">
        <option value="India">India</option>
        <option value="canada">Canada</option>
        <option value="usa">USA</option>
      </select>

      <label for="email">Email</label>
      <input type="text" id="email" name="email" placeholder="Your Email">
      
      <label for="subject">Subject</label>
      <input type="text" id="subject" name="subject" placeholder="Write something..">
      
      <label for="message">Message</label>

      <textarea id="message" name="message" placeholder="Write something.." style="height:200px"></textarea>
  
      <input type="submit" value="Submit">
    </form>
  </div>
  <div class="footer">
    {%for i in socialmedia%}
    {% if i.Socialmedia_text == "google" %}
    <a href="mailto:{{i.Socialmedia_url}}" target="_blank" class="fa fa-google"></a>
    {% endif %}
    {% if i.Socialmedia_text == "github" %}
    <a href="{{i.Socialmedia_url}}" id="fagithub" class="fa fa-github"></a> 
    {% endif %}
    {% if i.Socialmedia_text == "Linkedin" %}  
    <a href="{{i.Socialmedia_url}}" id="falinkedin" class="fa fa-linkedin"> </a>  
  {% endif %}
  {% endfor %}  

  
  </div>  
  
    

</body>

</html>    

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<title>PROFILE</title>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
<link rel="stylesheet" type="text/css" href="{% static 'css/1.css' %}">    
</head>


<body> 
  


<header>
<div class="topnav" style="background-color:dodgerblue">
    <a class="active" href="{% url 'profile:home'  %}" style="color:white;">Sudha Mullapudi</a>
   <div class="login-container">
    <a class="active" href="{% url 'profile:contact'  %}" style="color:white;">Contact me</a>
    </div>   
  <!-- <a href="javascript:void(0);" class="icon" onclick="myFunction()">      
    <i class="fa fa-bars"></i>
  </a> -->
</div>



</header>



<div class="imgcontainer" id="element1" align="center">
  <div   class="avatar">
       <img src="{%static 'img/2.jpg'%}" height="610" width="400" alt="OpenPics">      
  </div>
</div>
   

<div>
  



<div class="container" id="element2" align = "left-side">
<div >
  <p><b>Profile Summary</b>:</p>
    <p>iam sudha Mullapudi </p>



  <p><b>College Name:</b></p>
    <p>Potti sriramulu chalavadi malikarjuna rao of college of engineering and technology</p>


  <p><b>Experience:</b></p>
    <p> 6months experience in web technology</p>



  <p><b>Project:</b></p>
    <p>efficient spectrum utilization on SUCR protocol on Matlab</p>



  <p><b>Certificate:</b></p>
     <p>Done workshop on PCB Desinging</p>
     <p>presentation on iot</p>


</div>
      

  </div>   
</div>


  <div class="footer">
  
    <a href="mailto:m9340908@gmail.com" target="_blank" class="fa fa-google"></a>
  
    
    <a href="https://github.com/sudha85" id="fagithub" class="fa fa-github"></a> 
     
    <a href="https://in.linkedin.com/in/sudha-mullapudi-451980202" id="falinkedin" class="fa fa-linkedin"> </a>  
  
  </div> 

</body>

</html>    